version = 1

[[annotations]]
path = [
    ".gitignore",
    ".gitattributes",
    ".github/**",
    "README.md",
    "USAGE.md",
    "demo.gif",
    "docs/index.html",
    "patches/dolphin-quicklook.patch",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Pir0c0pter0"
SPDX-License-Identifier = "GPL-2.0-or-later"
